version: '3'
services:
  db_data:
    image: busybox
    volumes:
      - /var/lib/mysql
  db:
    image: mysql:5.7
    volumes_from:
      - db_data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: uuushiro-app
      MYSQL_ROOT_PASSWORD: password

  # apt update
  # apt install mysql-client -y
  # mysql -uroot -hdb -ppassword でログインできる
  shell:
    image: debian:stretch
    tty: true